name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run tests
        run: docker compose run --rm api pytest

      - name: Lint
        run: docker compose run --rm api ruff check .